name: Build and Push Docker Image to Google Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      no_cache:
        description: 'Build without cache'
        required: false
        default: false
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        # 액션(Action) 사용
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Configure Docker to use gcloud as credential helper
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./sample_a
          file: ./sample_a/Dockerfile
          push: true
          platforms: linux/amd64 #단일 플랫폼 지정으로 불필요한 매니페스트 리스트가 생성되지 않습니다
          tags: |
            ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/sample_a:1.3
          #  ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/sample_a:latest
          no-cache: ${{ github.event.inputs.no_cache == 'true' }}
          provenance: false #provenance와 sbom이 비활성화되면 메타데이터용 추가 이미지들이 생성되지 않습니다
          sbom: false
